### ISSUE TITLE
Add result sinks for Telegram, Slack, Email

### ISSUE THREAD

**Issue by zelenin** [dshearer/jobber#153]
Make notification sender (jobbern) with some default providers (email, telegram, slack, webhook etc).

Configuration example:

```yml
[prefs]
  notifyProgram: jobbern

[notifications]
- my_email:
  provider: 'email'
  params:
    email: 'name@example.com'

- my_telegram:
  provider: 'telegram'
  params:
    chat_id: '123456789'
    token: 'abcdef123456'

- common_telegram:
  provider: 'telegram'

[jobs]
- name: "job#1"
  ...
  notification:
    - via: 'my_email'
    - via: 'my_telegram'
    - via: 'common_telegram'
      params:
        chat_id: '098765'
        token: 'abcdef123456'
```

**Comment by dshearer** [comment]
How do you feel about using YAML anchors/references?  Like this:
```
[notifySinks]
my_email: &my_email
    provider: 'email'
    params:
        email: 'name@example.com'

my_telegram_1: &my_telegram_1
    provider: 'telegram'
    params:
      chat_id: '123456789'
      token: 'abcdef123456'

my_telegram_2: &my_telegram_2
    provider: 'telegram'
    params:
      chat_id: '987654'
      token: 'abcdef987654'

[jobs]
- name: 'job#1'
   ...
   notifyOnError:
       - *my_email
       - *my_telegram_1
   notifyOnSuccess:
       - *my_email
       - *my_telegram_2
```

I'd like to drop the ability to override notify provider params in the job def, in order to reduce complexity.

**Comment by zelenin** [comment]
I agree with it. It's clear.

**Comment by dshearer** [comment]
Actually, I'm thinking of merging #179 into this.  We have a notion of "result sink", which is given the result of a run (success/failure), stdout, and stderr, and then does something with it.

(At the same time, I'm thinking of just making the whole jobfile pure YAML.)

```
prefs:
    ...

resultSinks:
    - &email_summary
        provider: email
        params:
            email: name1@example.com
            data: [summary]
                
    - &email_summary_and_stdout
        provider: email
        params:
            email: name2@example.com
            data: [summary, stdout]
    
    - &save_stdout
        provider: filesystem
        params:
            path: /some/dir
            data: [stdout]
            maxAgeDays: 10
    
    - &my_telegram
        provider: telegram
        params:
            chat_id: '987654'
            token: abcdef987654
            
    - &program
        provider: program
        params:
            path: /notifyHandler.sh
            
    - &socket
        provider: socket
        params:
            type: inet # or inet6, or unix
            spec: 12345 # port for inet/inet6

jobs:
    job#1:
      notifyOnError:
          - *email_summary
          - *my_telegram
      notifyOnSuccess:
          - *program
          - *socket
```
