### ISSUE TITLE
Tested job does not show up in log

### ISSUE THREAD

**Issue by chrisandchris** [dshearer/jobber#197]
Hi
First of all, thanks for this nice piece of software and all the time you invest in it!
I have the following configuration
```
[prefs]
notifyProgram: /notify.sh
runLog:
  type: memory
  maxLen: 500

[jobs]
- name: FooJob
  cmd: curl -X GET https://example.rg
  time: "0 0 * * * *"
  onError: Backoff
  notifyOnError: true
  notifyOnFailure: true
  notifyOnSuccess: true
````
I execute this commands:
```
jobberrunner ~/.jobber
jobber test FooJob
jobber log
```
I expect the tested job to show up in the logs, but it is not. Is there any reason for tested jobs to not show up in the log?
Background is: We are using jobber for a centralized task-execution solution (which mainly runs HTTP-Posts). For several reasons, we offer the ability to manually trigger a task through a Web UI. We are required to have logs about manual triggers (and the notifyProgram must be called).

Best regards
Chris
