### ISSUE TITLE
How to verify that notifyProgram is being called?

### ISSUE THREAD

**Issue by ihsw** [dshearer/jobber#201]
Hi, my jobber config lists all notify options (`notifyOnSuccess`, `notifyOnError`, `notifyOnFailure`) to true but it doesn't look like the `notifyProgram` is being called at all. 

Can you provide guidance?

**Comment by axelchalon** [comment]
hi, I have the same issue; `notifyProgram` isn't executed on failure

```yaml
[prefs]
  notifyProgram: /home/me/bin/jobs/handleJobberError.sh

[jobs]
- name: daily job
  cmd: '/home/xx/bin/jobs/daily.sh'
  time: '0 35 18 * * *'
  onError: Continue
  notifyOnError: true
  notifyOnFailure: true
```

The program has correct execution permissions. Tester with Jobber v1.2.1 and v1.3.2, Arch Linux.
