### ISSUE TITLE
pref/jobOutput: Write job output to disk.

### ISSUE THREAD

**Issue by dshearer** [dshearer/jobber#25]
- Should be possible to have jobber write each job's stdout and stderr to disk.
- Only job owner can read logs for that job.

**Comment by dshearer** [comment]
This is tricky to do securely, especially if the user can specify where the logs are written.

**Comment by stephane-martin** [comment]
well, you could keep the job results in an internal database (eg boltdb) owned only by jobberd, and give users access to the results through a jobber command. each job execution could have an execution UUID, and then "jobber stdout UUID" would give the stdout output for that execution...

**Comment by nickmcdowall** [comment]
👍  For writing job runs and output to file please

**Comment by dshearer** [comment]
FYI I plan to get this done.  It's taken a while b/c I had to rearchitect the damn thing.

**Comment by dshearer** [comment]
```
[prefs]
jobOutput:
    stdout: &outputHandler
        handler: plaintextFiles
        maxAgeDays: 90
        dirPath: /my/job/output
    stderr: *outputHandler

[jobs]
- name: ForgetStdout
   ...
   output:
        stdout: null
```
