### ISSUE TITLE
Program Arguments

### ISSUE THREAD

**Issue by sabrehagen** [dshearer/jobber#263]
The jobfile format specifies

```yaml
    - &program
        type: program
        path: /notifyHandler.sh
```

for program invocations. It would be desirable to invoke the specified program with arguments. Can the jobfile format be expanded to support

```yaml
    - &program
        type: program
        path: /notifyHandler.sh
        args: [args]
```
for flexibility please?
