### ISSUE TITLE
Job gets repeated during the specified minute

### ISSUE THREAD

**Issue by D-K-E** [dshearer/jobber#306]
I have a schedule of the following type:
```yaml
TweetPersian:
    cmd: bash Path/to/tweetpersian.sh
    time: '* 10 09 * * *'
    onError: Backoff
    notifyOnFailure:
      - type: filesystem
        path: /path/to/jobber-failures
        data:
          - stdout
          - stderr
        maxAgeDays: 10
```
It is a schedule for a twitter bot. I noticed that the bot keeps tweeting during the minute, that is between 09:10-11, it kept tweeting. Is this the intended behavior ? Should I specify a second as well if I want it to tweet only once at 09:10 ?
