### ISSUE TITLE
Improve list command

### ISSUE THREAD

**Issue by ckotte** [dshearer/jobber#311]
It would be nice if jobber would return a non-zero return code if the job isn't found.

I use healthchecks like this in a my jobber Docker containers:
```
healthcheck:
      test: ["CMD-SHELL", "jobber list letsencryt_renewal"]
      interval: 10s
      timeout: 5s
      retries: 5 
```

However, the command returns always 0; also if a job doesn't exist. Because I build the jobs dynamically based on environment variables, it would be nice if jobber would explicitly check if the given job exists.

**Comment by ckotte** [comment]
I can use the cat command..

```
healthcheck:
      test: ["CMD-SHELL", "jobber cat letsencrypt_renewal"]
      interval: 10s
      timeout: 5s
      retries: 5
```
