### ISSUE TITLE
Missing information about logPath in documentation

### ISSUE THREAD

**Issue by ckotte** [dshearer/jobber#313]
There's no information about logPath in the documentation https://dshearer.github.io/jobber/doc/v1.4/

Are there also parameters like ```maxFileLen``` and ```maxHistories``` for this? If not, can this file grow indefinetly??

```
prefs:
  logPath: /home/bob/jobber/jobber.log
  runLog:
    type: file
    path: /home/bob/jobber/runlog
    maxFileLen: 100m
    maxHistories: 2
```
