### ISSUE TITLE
jobber reload doesn't update the program that's used

### ISSUE THREAD

**Issue by ckotte** [dshearer/jobber#320]
Old script:
```
  letsencrypt_renewal_test:
    cmd: bash -c "/usr/bin/certbot --text --non-interactive --no-bootstrap --no-self-upgrade certonly --webroot --webroot-path=/var/www/letsencrypt   --renew-by-default   -d abc.com
    time: '0 */1 * * * *'
    onError: Continue
    notifyOnSuccess:
      - type: program
        path: /usr/local/bin/send_email.sh
    notifyOnError:
      - type: program
        path: /usr/local/bin/send_email.sh
```

New script:
```
  letsencrypt_renewal_test:
    cmd: bash -c "/usr/bin/certbot --text --non-interactive --no-bootstrap --no-self-upgrade certonly --webroot --webroot-path=/var/www/letsencrypt   --renew-by-default   -d abc.com
    time: '0 */1 * * * *'
    onError: Continue
    notifyOnSuccess:
      - type: program
        path: /usr/local/bin/send_jobber_email.sh
    notifyOnError:
      - type: program
        path: /usr/local/bin/send_jobber_email.sh
```

The old script is still used after jobber reload. I have to delete the job, reload jobber, add the job again with the new script, and reload jobber.
