### ISSUE TITLE
notifyOnSuccess/Failure not supported as seq

### ISSUE THREAD

**Issue by catalinmer** [dshearer/jobber#322]
Hi,
I have the following job definition:
```yaml
[jobs]
- name: myjob
  cmd: |
    cp /a /b
    until [ $? -eq 0 ]; do
      echo "retry"
      sleep 1
      cp /a /b
    done
  time: '00 50 12 * * *'
  notifyOnSuccess:     
    - type: stdout     
      data:            
        - stdout       
        - stderr       
  notifyOnFailure:     
    - type: stdout
      data:     
        - stdout
        - stderr
```
but if i run jobber reload i get:
```
#jobber reload
Call to Jobber failed: Failed to parse "jobs" section: yaml: unmarshal errors:
  line 12: cannot unmarshal !!seq into bool
  line 17: cannot unmarshal !!seq into bool
```
i'm using latest version from docker container, 14.4
Would you be able to help me? thanks
