### ISSUE TITLE
Jobber not executing actions, just printing the commands

### ISSUE THREAD

**Issue by itchy2** [dshearer/jobber#323]
Hi all,

first of all: I'm new to jobber and I expect the issue in front of my screen.

I have the following docker-compose file to "learn"/practice jobber:

```
version: '3'

services:
  jobberorg2:
    image: blacklabelops/jobber
    container_name: jobberorg2compose
    restart: always
    environment:
      - JOB_NAME1=TestEcho
      - JOB_COMMAND1=date
      - JOB_TIME1=* * * * * *
```

Result: Jobber ist printing date. So it behaves like `echo date`
	  
Alternatively I tried to put the command into a separate file and stored it into a shared volume with the jobber container:

```
version: '3'

services:
  jobberorg3:
    image: blacklabelops/jobber
    container_name: jobberorg2compose
    restart: always
    volumes:
      - /home/holger/docker/datapath/jobber2/jobberuser:/home/jobberuser
    environment:
      - JOB_NAME1=TestEcho
      - JOB_COMMAND1=bash /home/jobberuser/test/job.sh
```

my job.sh contains only `date`

Result: `jobberorg2compose | root: bash /home/jobberuser/test/job.sh`

Has anybody a hint for me what I'm doing wrong? Finally I want to end up with a script called every minute.

Thanks and kind regards
Itchy2
