### ISSUE TITLE
YAML anchors need to precede any references to them

### ISSUE THREAD

**Issue by sebastian13** [dshearer/jobber#326]
Hi,

there seems to be a mistake in the `.jobber` example in the [documentation](
https://dshearer.github.io/jobber/doc/v1.4/#overview). I couldn't get the `resultSinks` to work until I've found the [following on stackexchange](https://stackoverflow.com/a/53743278/8940679).

> In YAML all anchors ( those tokens starting with &) need to precede any references to them (using aliases, the tokens starting with *) in the file.

I was able to use resultSinks by putting them above jobs:

```
version: 1.4

resultSinks:
  - &email
    type: system-email

jobs:
  HealthPing:
    cmd: curl -m 5 --retry 2 https://healthchecks....
    time: '30'
    notifyOnError:
      - *email
```

If you can confirm this, please move the `resultSinks` above `jobs` on the documentation as well.
