### ISSUE TITLE
Specify shell or allow setting all jobs to automatically source a file/profile?

### ISSUE THREAD

**Issue by MostHated** [dshearer/jobber#328]
Hey there,
 I seem to be having a bit of an issue finding a reliable way to access environmental variables and functions from jobs. I see that the jobs return back $SHELL as /bin/sh. Is there some way I can make all jobs run under a different shell (such as zsh) so that it can automatically pick up my .zshenv file or if not that, at least pick up the /etc/bash.bashrc or something along those lines, straight from the cmd line within the job file so that I don't have to make each job individually source it?

Thanks,
-MH

**Comment by MostHated** [comment]
I just thought of this, so I wanted to post it while I was thinking of it. Being able to have settings such as the ones below would be awesome.

```yaml
prefs:
  shell: /bin/zsh # Shell for all jobs
  source: $HOME/.jobberenv # Sourced for all jobs

jobs:
  myjob1:
     cmd: $HOME/scripts/job1.zsh
     source: $HOME/.job1env # Sourced for specific job
     time: '*/30 * * * * *'  
     onError: Continue 
  myjob2:
     cmd: $HOME/scripts/job1.xsh
     shell: /usr/bin/env xonsh # Shell for this job
     source: $HOME/.job2env # Sourced for specific job
     time: '*/30 * * * * *'  
     onError: Continue 
```
